services:
    _defaults:
        public: false

    Runroom\CookiesBundle\Admin\CookiesPageAdmin:
        public: true
        arguments: [null, Runroom\CookiesBundle\Entity\CookiesPage, null]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Cookies' }

    Runroom\CookiesBundle\Controller\CookiesPageController:
        public: true
        arguments:
            $service: '@Runroom\CookiesBundle\Service\CookiesPageService'
            $renderer: '@Runroom\RenderEventBundle\Renderer\PageRenderer'
        tags: [controller.service_arguments]

    Runroom\CookiesBundle\Service\CookiesPageService:
        arguments:
            $repository: '@Runroom\CookiesBundle\Repository\CookiesPageRepository'
            $handler: '@Runroom\FormHandlerBundle\FormHandler'
        tags: [kernel.event_subscriber]

    Runroom\CookiesBundle\Service\CookiesService:
        tags: [runroom.cookies.service]

    Runroom\CookiesBundle\Repository\CookiesPageRepository:
        arguments:
            $registry: '@doctrine'
        tags: [doctrine.repository_service]
